### ISSUE TITLE
Travis-CI passing logo is deceptive

### ISSUE THREAD

**Issue by jflory7** [ritjoe/hfoss#114]
The Travis-CI logo in the README.md file is hooked into the Travis-CI testing repository from the old repository for this class, [`decause/hfoss`](https://github.com/decause/hfoss). The README "passing" logo shows the status of that [Travis project](https://travis-ci.org/decause/hfoss).

As discussed in FOSShours, either the Travis-CI repo needs to be created and then updated for `ritjoe/hfoss` or the logo should be removed from the README file (and subsequent `.travis.yml` file).

**Comment by liam-middlebrook** [comment]
:+1: 

I think that @ritjoe should look into enabling Travis on this repository. With the automated YAML validation written into ofCourse this will also help screen out invalid YAML files before they get merged in.
