### ISSUE TITLE
Add PGP/gpg links to resources

### ISSUE THREAD

**Issue by ritjoe** [ritjoe/hfoss#310]
As we get videos completed of GPG key management tasks using GnuPG, Seahorse, etc, add links to those to course resources.

Also add primers like

https://fedoramagazine.org/gnupg-a-fedora-primer/

Some links may end up refactored into lectures.

**Comment by ritjoe** [comment]
The full series, as best I can tell:

https://fedoramagazine.org/gnupg-a-fedora-primer/
https://fedoramagazine.org/gpg-using-your-key/
https://fedoramagazine.org/gpg-key-management-part-1/
https://fedoramagazine.org/gpg-key-management-part-2/

h/t to @cprofitt

**Comment by CoffeeFrame** [comment]
I'm confused on how this was opened before the course had started.

**Comment by ritjoe** [comment]
Not in resources, but there's a wiki page now:

https://github.com/ritjoe/hfoss/wiki/pgp
