### ISSUE TITLE
Color Legend For Syllabus Schedule

### ISSUE THREAD

**Issue by Awmusic12635** [ritjoe/hfoss#316]
I think it would be useful to have a legend for what the colors on the schedule mean. There are multiple items highlighted with various colors, however they are never defined what they mean.

I'd be willing to make the change if you can tell me what the various colors mean. 

Picture for reference:

<img width="994" alt="syllabus_ _the_rit_hfoss_development_course_documentation" src="https://cloud.githubusercontent.com/assets/7191902/22209701/6de59426-e155-11e6-8eb5-52de0744c73a.png">

**Comment by ritjoe** [comment]
On Mon, Jan 23, 2017 at 07:19:39AM -0800, Awmusic12635 wrote:
> I think it would be useful to have a legend for what the colors on the schedule
> mean. There are multiple items highlighted with various colors, however they
> are never defined what they mean.
> 
> I'd be willing to make the change if you can tell me what the various colors
> mean.
> 
> Picture for reference:
> 
> syllabus_ _the_rit_hfoss_development_course_documentation

As noted in IRC, I play fast and loose with the color categories. There are,
for instance, still events listings I need to enter before I worry about the key.

Even so, it's a good goal and if you can help me work towards that, all the
better, that's totally in the spirit of the course!  (Though to be fair I
should note I've not been giving bugfix credit for bugs that one identifies
oneself, because it offers perverse incentives both to the student and the
instructor: Someone else needs to have filed the bug.).

That said, the 'class' attribute of the corresponding <p> tags gives a
pretty clear indication as to what those colors are *supposed* to be used
for:

    hfoss$ git log -p templates/syllabus.mak | grep "<p class" | sort | uniq -c | sort -nr 
    304                  <p class="topic ">
    208 +                <p class="topic ">
    110 -                <p class="topic ">
     53                  <p class="topic">
     38 +                <p class="topic">
     30                  <p class="topic special">
     25 +                <p class="topic special">
     19 -                <p class="topic special">
     19 +                <p class="topic cancelled">
     19 -                <p class="topic cancelled">
     19 -                <p class="topic">
     18                  <p class="topic cancelled">
     18 +                <p class="special">
     17 +                <p class="special ">
     15 +                <p class="topic hackathon">
     15 -                <p class="topic hackathon">
     12                  <p class="topic guest">
     12 -                <p class="special">
      9 +                <p class="topic guest">
      9 -                <p class="topic guest">
      9 -                <p class="special ">
      9                  <p class="special">
      8 +                <p class="">
      6                  <p class="topic hackathon">
      6 +                <p class="hackathon">
      6 +                <p class="hackathon ">
      6 +                <p class="cancelled">
      6 -                <p class="">
      5                  <p class="hackathon">
      4                  <p class="special ">
      3 -                <p class="hackathon">
      3                  <p class="hackathon ">
      3 -                <p class="cancelled">
      3                  <p class="">
      2 -                <p class="hackathon ">
      1 +      <p class="topic ${topic.get('special', '')}">


I remain unclear on the use of, eg, "topic special" vs just "special" or "topic hackathon" vs just "hackathon".

**Comment by bxs9775** [comment]
Hello. Is anyone actively working on this? If not, would anyone mind if I try looking at it for the bugfix assignment? @ritjoe would this be an appropriate task for the Bugfix assignment as it is an enhancement more than a bug fix? Thank you.

**Comment by Awmusic12635** [comment]
I was originally however I have been a bit overwhelmed by work. If @ritjoe allows it, go for it.

**Comment by bxs9775** [comment]
Thank you.

**Comment by ritjoe** [comment]
fine with me

**Comment by bxs9775** [comment]
Ok, I'll start working on it.

**Comment by bxs9775** [comment]
From what I can see, the schedule uses 5 main classes topic, special, hackathon, guest, and cancelled. The "topic" class appears to affect margins, but not color. "Special" sets the background-color to yellow, "hackathon" sets the background to orange, "cancelled" sets the background color to red (text can be hard to read against this background), and guest sets the background to light green. There is also a "vaycay" class that sets the background to light grey, but it does not show up in the list of tags @ritjoe collected from the page, so I am not sure whether to put in the legend or not.

Currently, I made a Legend section under the schedule and labeled the section with a level 3 header. I think there should be a label/header for the legend, but I am not sure if it should be level 3 or something else. What do you think? Below the header, there is a one column table with a labeled element with the corresponding class, the way the table is formatted it can become hidden by the index/table of contents for a time when you scroll past.

I have the changes I made so far on [my fork ](https://github.com/bxs9775/hfoss)of the project. I want to revise the page more before I make a pull request. In addition, so far I have only checked the page by copying over the code and css style references into an empty HTML file and looking at it in the browser. I will want to figure out how to run OfCourse to perform a more thorough program test tomorrow.

**Comment by bxs9775** [comment]
I made a pull request for the legend table I developed for the syllabus page. The pull request is https://github.com/ritjoe/hfoss/pull/363. The request is not set-up to close the issue after it is pulled, as my code for the legend may be in need of additional review.
