### ISSUE TITLE
Bug Report: Links inside of QuickStart Wiki Broken

### ISSUE THREAD

**Issue by smendez93** [ritjoe/hfoss#416]
Inside of the wiki, under the section for sugar quick starts, there are two links that don't lead anywhere. These two links just open the current page in a new tab. 
The links can be found under the "Download sugar-quickstart source code" section of the wiki.
The link text and the intended paths are as follows:

[Liam Middlebrook's](http://github.com/liam-middlebrook/sugar-quickstart)--> http://github.com/liam-middlebrook/sugar-quickstart
[FOSSRIT organization.](http://github.com/FOSSRIT/sugar-quickstart) --> http://github.com/FOSSRIT/sugar-quickstart

**Comment by ritjoe** [comment]
Closed by https://github.com/ritjoe/hfoss-wiki/commit/1f20a178437146aa29b2704847ba8d64dfcaf3b9
