### ISSUE TITLE
Assignments.yaml is overpopulated

### ISSUE THREAD

**Issue by liam-middlebrook** [ritjoe/hfoss#45]
It looks like you have assignments "active" (not commented out) that are not due yet. This causes the participants page to list out that a higher number of blog posts are currently expected than actually are.

**Comment by ritjoe** [comment]
And?

**Comment by ritjoe** [comment]
I guess what I'm trying to ask is:  Do you propose we deal with this through documentation, or through incorporating due dates into ofcourse, or what?

**Comment by liam-middlebrook** [comment]
I think you should just comment out those assignments until they are due. Like how some of them [already are](https://github.com/ritjoe/hfoss/blob/master/assignments.yaml#L9).

**Comment by ritjoe** [comment]
On Tue, Sep 22, 2015 at 07:01:27AM -0700, Liam Middlebrook wrote:
> I think you should just comment out those assignments until they are due. Like
> how some of them already are.

OK, I probably will.

But then, how will the *next* instructor know to do that, once you're not
around to tell her that that's the way you think it should be done?

I'll put you down for "documentation" on this one ;-)
