### ISSUE TITLE
Schedule should include Blog Posts and names

### ISSUE THREAD

**Issue by ReginaTL** [ritjoe/hfoss#489]
I know that the blogs are supposed to be done every week on Wednesday but I think it would be easier if the blogs, with the proper name that we are supposed to use in the yaml files, are on the schedule in the due dates. I feel the schedule should be an at a glance overview of the course and I feel it would be helpful as a reference when submitting assignments to have those names there.

**Comment by ritjoe** [comment]
I've added blog due dates to the schedule for quite some ways out now.

I'm opening upcoming assignments well in advance at

http://hfoss.rocfoss.org/participants/

which I also show and to which I make frequent reference during classtime. 

The exact form of the YAML key value for each assignment is as seen on that page, which is generated from assigments.yaml in the course repository, a copy of which is in each fork or clone of the course.
