### ISSUE TITLE
Suggestion - add an exercise about dealing with merge conflicts

### ISSUE THREAD

**Issue by gen1e** [ritjoe/hfoss#661]
So something I was thinking about while my group is dealing with merge conflicts (like right this second). Not many students actually know how to deal with a git merge conflict. They don't know what the merge tags do and don't know how to fix the file to resolve the merge. Perhaps adding an exercise in the beginning when we go over git with a simple merge conflict that they have to resolve on their own after going over it in class. You can provide an example repo with simple merge conflicts that they fork then resolve on their fork to show they can handle merge conflicts. A blog post with their explanation of how they did the merge would likely be helpful. I find that a lot of students in this college have issues with merge conflicts and don't really know how to resolve them, even the upperclassmen so having an exercise like this would be very beneficial.

**Comment by gen1e** [comment]
Sorry for the delay in response. This looks great! The only thing is I would suggest them actually going in and editing the pre-existing file instead of just replacing it. This way they get used to going through a file and dealing with it because if something comes up in their group project, they will likely have to deal with it by editing the file.

**Comment by ritjoe** [comment]
Closed with https://github.com/ritjoe/hfoss/wiki/merge-conflict-resolution-exercise/61cff626e291c88cd7ee5d7dcc31f9b42e27d8fa
