### ISSUE TITLE
Add jwf Matrix article link to IRC.md in the wiki

### ISSUE THREAD

**Issue by ritjoe** [ritjoe/hfoss#665]
Topic covers it. Too late tonight for me to do it justice after several rounds of minor tweaks to the doc as it is. I mean the IRC-for-the-21st-century one at opensource.com

**Comment by ct-martin** [comment]
@ritjoe remember to add a note on `!storepass` since iirc that's not in the article

**Comment by ritjoe** [comment]
close by https://github.com/ritjoe/hfoss/wiki/IRC/bb2fc58434df39e2102befcf4345c2d3f0155a0b

@ct-martin sorry, I'm not familiar with !storepass

It's still manually done rather than automated, but I try to keep this repo's wiki synched reasonably well with https://github.com/ritjoe/hfoss-wiki so pull requests can be submitted against that.

**Comment by ct-martin** [comment]
@ritjoe https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#how-do-i-registeridentify-to-nickserv
