### ISSUE TITLE
Blog Post Count Invalid for ry60003333

### ISSUE THREAD

**Issue by liam-middlebrook** [ritjoe/hfoss#75]
It looks like @ry60003333, has a blog feed setup that doesn't play nicely with [feedparser](https://github.com/kurtmckee/feedparser).

**Comment by ry60003333** [comment]
It looks like the [W3C validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.allgofree.org%2Fblog%2F%3Ffeed%3Drss2) can't grab the feed either, does feedparser support TLS 1.2?

**Comment by ry60003333** [comment]
I've changed my URL to use a non-HTTPS URL for now; @msoucy says that this is fixed in an update to Python.

**Comment by msoucy** [comment]
Closed via #94
