### ISSUE TITLE
Add Matrix nickserv infoto wiki

### ISSUE THREAD

**Issue by ct-martin** [ritjoe/hfoss#793]
@jwflory 's article is a great start to Matrix/Riot, one more thing that helps a lot is [how to auto-authenticate with Nickserv](https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#how-do-i-registeridentify-to-nickserv). This would be a good addition to the IRC wiki page

**Comment by deejoe** [comment]
On Mon, Jan 13, 2020 at 05:30:10PM -0800, Christian Martin wrote:
> @jwflory 's article is a great start to Matrix/Riot, one more thing that helps
> a lot is how to auto-authenticate with Nickserv. This would be a good addition
> to the IRC wiki page

There currently is a link in IRC.md to:

https://opensource.com/article/17/5/introducing-riot-IRC

Is this what you mean? If not, could you provide a link, please?

Thanks!

-- 
Joe

**Comment by jwflory** [comment]
Christian linked this in his original comment, maybe it didn't appear in the email.

https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#how-do-i-registeridentify-to-nickserv

**Comment by ct-martin** [comment]
@deejoe : @jwflory was correct; there was a link in the original post that probably didn't get sent over email

**Comment by ritjoe** [comment]
Ah, right. Thanks @jwflory. My bad for not looking at the HTML part of the message.  

Sorry, @ct-martin.

**Comment by ct-martin** [comment]
No problem :)

--
Christian Martin (Phone)

**Comment by ritjoe** [comment]
Done. Thanks.
