### ISSUE TITLE
Spring 2020 catch-all issue

### ISSUE THREAD

**Issue by ritjoe** [ritjoe/hfoss#891]
This is meant to provide yet another way for anyone in the course to ask a question or make a comment. All current students should feel absolutely free to add to this issue to ask or answer a question or raise a concern.

We may move discussion of something raised here into its own separate issue, or into a different channel, but this is a good first start so that you do not have to worry about whether and how to create a new issue.

(Like the rest of this GitHub repository, this is public, so you may wish to send the instructor confidential email instead.)

**Comment by ritjoe** [comment]
@cja1093 @eza5640 @zsd7200 @zethra @BlueJay89 @jrtechs @DennisSSDev @iggyvolz @ymoullec @iclare

**Comment by ritjoe** [comment]
@cja1093 @eza5640 @zsd7200 @zethra @BlueJay89 @jrtechs

I do not see any of you in the list of those who are *watching* this repo. You probably should do so.

https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-repositories

**Comment by BlueJay89** [comment]
What repo?

**Comment by deejoe** [comment]
On Wed, Apr 01, 2020 at 04:52:45PM -0700, BlueJay89 wrote:
> What repo?

If you're getting notifications by email, as I am, then there will be a "view it on GitHub" link in the footer of the message. 

Following that will take you to one of the web views of the GitHub repository in question. Near the top right of those views will be a set of items: Watch, Star, Fork, each with a count of how many times the repo has been watched, starred, or forked. Clicking the larger left-hand portion of each will effect that action indicated by that word, for your account, prompting you to log in if necessary to complete that action. Clicking the smaller portion with the number will give a display of what accounts have already done each.

Presumably other ways of getting notifications offer similar ways to go to the repo's web pages.

Please let me know if that answers your question well enough or not.

-- 
Joe

**Comment by ritjoe** [comment]
OK, thank you Jeffery and Matt for watching!

@cja1093 @zsd7200 @zethra @BlueJay89 you still need to set this (the hfoss) repo to "watch" status.

**Comment by ritjoe** [comment]
@cja1093 @eza5640 @zsd7200 @zethra @BlueJay89 @jrtechs @DennisSSDev @iggyvolz @ymoullec @iclare

As we discussed yesterday, the emails I've sent to floss-seminar are getting flagged as potential spam/spearphishing, apparently due to my attaching the class meeting logs or due to including links to those logs (or both?).

You can access the mailing list postings, including the attachments, at

https://lists.rit.edu/mailman/private.mmcgi/floss-seminar/

though you will have to log in with your subscribed email address and the password you set for the list.

If you need a password reminder you can get that through

https://lists.rit.edu/mailman/options.mmcgi/floss-seminar
